-- Firestore'dan Supabase'e Çalışan Import
-- Bu SQL'i Supabase SQL Editor'de çalıştırın
-- Sadece çalışan isimleri (name kolonu)

INSERT INTO calisanlar (name) VALUES
('2.Kat Çay Ocağı - 1242'),
('İmar ve Şehircilik Müdür V. Hayrettin BAHŞİ - 1110'),
('Plan ve Proje Müdür V. Mehmet ATALAY - 1121'),
('Muhtarlık İşleri Müdür V. Kadir ÇIRA - 1247'),
('Yasemin ÖNEY - Özlem GÖRÜCÜ - 1123'),
('Ahmet KARBUZ - 1007'),
('Murat Manav - 1140'),
('Emre İPEK / Kübra TAT - 1313'),
('Fen İşleri Müdür V. Harun ERBİ - 1154'),
('Süleyman DUKLUK - 1120'),
('FAX - 421'),
('Özel Kalem Yazı İşleri: Şef Hüsnü ŞAHİN - 1312'),
('Yazı İşleri Servisi: Erçin ULUKAYA - 1205'),
('Başkan Yardımcısı Ali ÖZKAYACAN - 1326'),
('Gökhan GÖKÇE - 4447'),
('Ebru İPEK - 4440'),
('Yazı İşleri Servisi: Adile Cebeci - 1149'),
('Bilgi İşlem Müdür V. Hüseyin ACAY - 1148'),
('Pınar Sedef ÜNAL - Azize ZENKİN - 1142'),
('Ruhsat Arşiv: Serap ERKUŞ - Enver ÖZTÜRK - Mehmet Canöztürk - 1155'),
('Merve KEKLİK - 1122'),
('Kaçak Yapı: Hidayet AYVERDİ - 1215'),
('Başkan Yardımcısı Hakan BİLGİ - 1919'),
('Muzaffer YURTSEVEN - Ayşe Kübra YÜZTAŞ - 1222'),
('Mali Hizmetler Müdürlüğü Sekreterlik: Cansel GÜNEŞ - 1220'),
('Doktor Odası - 1090'),
('Kübra GÜNERİ - 1622'),
('Zabıta Müdür V. Tarkan GÜMÜŞ - 1001'),
('Satınalma: Selçuk ÖCÜ / İbrahim ARSLANTAŞ - Melek İNCE - 1231'),
('Gülsüm TEBER - Ferhat CANKARA - 1251'),
('Ödemeler: Emre ALKAN - 1211'),
('1.Kat Çay Ocağı - 1145'),
('Toplantı Odası - 1410'),
('G. Gülfem DURAK - Oğuz TAŞAR / Mehmet Akif KARABAY - Temel YETİM - 1241'),
('Rabia CEBECİ / Fatma ÖZTÜRK - 1106'),
('Arif BAHŞİ - 1217'),
('ARAÇ HAVUZ - 1025'),
('Harita: Mustafa YILDIRIM (Tevhit) - 1118'),
('Enver ALTUNDAĞ (İnşaat Teknikeri) - Mehmet SOLAKLAR - 1107'),
('Yazı İşleri: Halil ÇELİK - 1146'),
('Hacer BÜYÜKŞAHİN (Elektrik Mühendisi) - Nurten YAĞAN (İnşaat Mühendisi) - 1126'),
('Kalem: Sebahattin EKİZ / Ahmet SARICA - Osman KOYUN - İsmet TOLU - 1000'),
('Evrak Kayıt: Hasan TORLAK - Selim AĞAR - 1208'),
('İsmail KALKAY (İnşaat Mühendisi - Yapı Denetim) - Mehmet UYHAN (Yapı Denetim) - 1151'),
('Yasin AKBABA (Tahakkuk Servisi) - 1032'),
('Donanım Destek Servisi: Ahmet ÖZKAN - Can GÜRSES - 1143'),
('Başkan Yardımcısı Sekreteri Esra ÇİL - 1323'),
('Güvenlik: Giriş Kapı - 1044'),
('Arif ÇİNİ (Taşınmaz İhaleler) - 1244'),
('Banko: Emine BELEN - 4441'),
('Sebahattin Ekiz - 1017'),
('Basın Ofisi: Fatma Ezgi ÇOT - 1015'),
('Ramazan BOZ - 1230'),
('Gelir Takip Şef İrfan KAŞLI - 1048'),
('Satınalma: Hatice YILDIRAN - 1253'),
('Başkanlık Sekreteri Behiye YARAŞÇI - 1400'),
('Veterinerlik: Yunus Emre YAYLA - 1027'),
('Satınalma Şef Mehmet KARA - 1240'),
('Hanife ÖZKAN - 1103'),
('Sağlık İşleri Birimi: Fatmana TIRAŞ TÜRKER - Ahmet ALTINER - 1080'),
('Nar Masa Süleyman ÇAKAN - 4444'),
('Emlak ve İstimlak Müdür V. Hüseyin SİVRİ - 1246'),
('Erdi BAHŞİ - 1132'),
('Derya AKIN - 1006'),
('Ön Onay: Mimar Sezen KÜÇÜKBAŞKAN / Baki UZUNOĞLU - Fulya Barut / Hale FIRAT - 1112'),
('Eray DİNSEL - Aydın KIVRIM - 1131'),
('BAŞKAN - 1406'),
('Evlendirme: Mustafa ALDEMİR - 1022'),
('Rahime DEKE - Ümit TUTAR / Murat YALDIZ - 1319'),
('Şef Ramazan YANAR - 1043'),
('Yazı İşleri: Havva KILINÇ - Alper Barut - 1223'),
('Hayal YURTSEVEN - 1226'),
('İşkur Servisi: Eylem İMİR - 1009'),
('Binnur UYGUN - 1210'),
('Diş Birimi: DT. Şenel GÜNAL İLTAŞ - Serpil ÜNEŞ - Pınar KÜÇÜKTEKİN - 1046'),
('Zemin Kat Çay Ocağı - 1029'),
('Süleyman ÇELİK / Harun ÖNKAL - Hanife Esma İNCE - 1233'),
('Destek Hizmetleri Müdür V. Erkan ŞİMŞEK - 1232'),
('Boş Birim - 444'),
('Başkan Yardımcısı Sekreteri Funda TÜFEKÇİ - 1327'),
('Özel Kalem Yazı İşleri: Dilek KÜÇÜKBAŞKAN - Ramazan KÜÇÜKBAŞKAN - Fatma EROĞLU - 1318'),
('3.Kat Çay Ocağı - 1255'),
('Adem ERKUŞ - Doğan AKINCI - 1228'),
('İmar ve Şehircilik Müdürlüğü Sekreterlik: Sevgi UZUNOĞLU - Zeren DEMİRCİ - 1119'),
('Hayriye DÖLEN SÖNMEZ (Makine Mühendisi) / Ümit KÜÇÜKÇAKAL - 1111'),
('Hukuk İşleri Müdürü V. Ramazan DÖNMEZ - 1310'),
('Merve Kıvrak(İş Yeri Rushatı) - Hüseyin ÖZEN (Harita Teknikeri) - 1218'),
('Oğuzhan FIRAT (Tahakkuk Servisi) - Durmuş Gürkan (Tahakkuk Servisi) - 1033'),
('Havva KESER - 1224'),
('Afet İşleri Müdür V. İbrahim TEKŞAN - 1307'),
('Mehmet Ali TUNÇ - 1207'),
('Suna Uysal - 1011'),
('Yazılım Destek Servisi: Selman KARADAĞ - Rauf KURT - 1147'),
('Teftiş Kurulu Müdür V. Cavit AKTAR - 1245'),
('Tahsilat: Doğan ÖZEN - 1028'),
('Plan ve Proje Müdürlüğü Sekreterlik: Meral TEKŞAN / Sekreter Ayşe GÜBEŞ - 1139'),
('Başkan Danışmanı - 1404'),
('Başkan Yardımcısı Ömer KIVRAK - 1322'),
('Şafak TOSUN ARSLAN - Melda SAPMAZ / Barış YÖNTER - 1624'),
('Mürüvvet YILMAZ - 1238'),
('İbrahim AKAN - Salih Saçkan (Ruhsat ve Denetim Arşivi) - Güllü ÇINAR - 1102'),
('Özel Kalem Müdürü Ömer DERELİ - 1403'),
('İş Yeri Ruhsatı: İbrahim AKBABA - Merdan AKPINAR - 1203'),
('Seher ATASEVEN (Harita Teknikeri) - Musa TEVKE - Helin ŞAHİN BARUT (Zemin ETÜT) - 1105'),
('Kazı İşleri: Alper YERLİ - Dursen Buse ARICA - 1138'),
('Recai KARA (Tahakkuk Servisi) - Osman YANAR (Tahakkuk Servisi) - Hasibe TOSUN (Tahakkuk Servisi) - 1041'),
('Başkan Sekreteri Nilüfer ÖZTÜRK - 2012'),
('Teknik Servis: Elektrik - 1523'),
('Neslihan BAYGÜL - 1236'),
('Sekreterlik: Raziye ŞİMŞEK - 1317'),
('Yusuf Yılmaz - Ömer AYA (KLİMACI) - 1527'),
('Santral: Ezgi Nur AKÇA - 1402'),
('Havvanur TEKİN - 4445'),
('Basın Ofisi: Mustafa Bürge - 1303'),
('Teftiş Kurulu Müdürlüğü Sekreterlik: Hanife ACAR - 1235'),
('Mehtap - Merve Keklik - Murat Doğan - 1256'),
('Güvenlik Odası - 1013'),
('İşkur Servisi: Aşkın GÖZE - 1010'),
('Meclis Üyeleri - 1314'),
('Ali ŞEKERLİ - Ummani TÜRKMENOĞLU - 1225'),
('Çiğdem AYHAN TOSUN - 1204'),
('Bordro Servisi: Abdullah Gümüş - Eda Deke - İsmail YILDIZ - 1250'),
('Sevgi ÇİÇEKDAĞI - Gülsüm KORKMAZGİL - Özgür Koyuncu - Ayşe BİLGİÇ - 1278'),
('Fen İşleri Müdürlüğü Sekreterlik: Canan SERBEST - 1100'),
('Başkanlık Çay Ocağı - 1405'),
('Numarataj: Hasan DÖNMEZ (Adres ve Adres Kodu) - Mustafa TATLI - 1128'),
('Basın Yayın ve Halkla İlişkiler Müdür V. Elif Figen YURTSEVEN - 1005'),
('Basın Danışmanı Veysi SAĞLAM - 2014'),
('İş Yeri Ruhsatı: Cem ŞAHİN - Ali ÇETİN - 1212'),
('Zeynep DOĞAN - 1008'),
('İlan Reklam Birimi: Zekeriya ALTIN - Tuna ÖZDEMİR - 1309'),
('Kademe - 443'),
('Harita: Hakan ÇİLOĞLU - 1104'),
('Tuğba Erdil - 1209'),
('Santral: Suzan AYAZ - 2511'),
('Alparslan ŞAHİN - 1136'),
('Yasin TEKELİ - 1152'),
('Ruhsat Denetim Müdür V. Murat ÇANKAYA - 1200'),
('Başkan Şoför Odası - 1412'),
('İklim Değişikliği ve Sıfır Atık Müdür V. Yalçın KAYA - 1306'),
('Mehmet Ali GÖKMEN - Doğan YENER / Hasan DÖNMEZ - Mustafa TATLI - 1124'),
('Veterinerlik Odası (Eski Bilgi İşlem Odası) - 1071'),
('Mali Hizmetler Müdürü Rabia KILIÇÇI - 1221'),
('Yazı İşleri Müdürü Nadire ÖZDEMİR - 1202')
ON CONFLICT (name) DO NOTHING;

-- Kaç kayıt eklendi kontrol et
SELECT COUNT(*) as toplam_calisan FROM calisanlar;

SELECT 'Çalışanlar başarıyla import edildi!' as mesaj;
